### ISSUE TITLE
Objective getting lost through objects/walls

### ISSUE THREAD

**Issue by krazykaze81** [rtcwmp-com/rtcwPro#213]
Seems to be recreated by Kris and Crumbs - we need to verify on our end

**Comment by natelo** [comment]
Does this issue occur when player that holds the docs, dies?

**Comment by wolf6542** [comment]
https://streamable.com/lezctl

**Comment by krazykaze81** [comment]
> Does this issue occur when player that holds the docs, dies?

Yes

**Comment by natelo** [comment]
This should resolve it: https://github.com/rtcw-nihi/ospx/pull/218

**Comment by krazykaze81** [comment]
Thanks @natelo

**Comment by krazykaze81** [comment]
Reopening as euro guys saw this on ice where docs fell into the wall breach on ice

**Comment by natelo** [comment]
As it was evident that docs fall under/inside objects I've added a small height so they drop from above instead of 0 .. in theory that should solve the issue where they end up in objects. 

Commit is here: https://github.com/rtcwmp-com/rtcwPro/commit/c8788d0f09cac5558862025f96359740fa4ed59d

**Comment by krazykaze81** [comment]
This hasn't happened in 1.2 yet, so I'm going to close this for now.
