### ISSUE TITLE
Intermittent involuntary crosshair movement

### ISSUE THREAD

**Issue by acelad88** [rtcwmp-com/rtcwPro#242]
### Description of the issue

The crosshair moves along the X and Y axis very quickly by itself. It seems like a mouse hardware issue, but **does not happen in other games, and does not even appear to occur in OSP**. Seems intermittent, so the best we can do is keep clipping it to try to identify any triggers. I'd say this has been happening once every ~3 games on RtCWPro for me, and going forward whenever I notice it, I'll try to clip it each time.

Now that a few players with different setups have reported it, I thought it a good time to create a ticket so we can try to pinpoint how and why it occurs.

My config is:

- Mouse: Logitech MX518 (400DPI)
- Running RInput 1.44 every time I play RtCW (https://fearless-assassins.com/files/file/1656-rinput/)

### Examples

- Adlad (Logitech MX518, RInput, 400DPI): https://streamable.com/ehjv72
- Bully (FinalMouse Ultralight 2, RInput): "Sometimes after getting revived or spawning, the mouse is forced into a different direction. I had a clip from the revive, but can't find it atm. Here's one after spawning:" https://www.twitch.tv/videos/876529420?t=0h32m4s
"Could be a vanilla rtcw issue, but I never experienced it on vanilla/shrub/osp as far as I know. I've used rinput on all these. On other games I have no issue either, without rinput"
- canhanc (Logitech G403, NO RInput): "The crosshair bug on first clip also happened to me, i was thinking my mouse was the problem apparently it isnt"
https://discord.com/channels/318798012455321602/731186601509781504/800340652457459723
- Graecos (Logitech MX518, RInput, 400DPI): https://youtu.be/XYamJrLkDBg?t=3 && https://youtu.be/dF9NZ5gHDEQ?t=11

**Comment by krazykaze81** [comment]
We need to test this after #270 is implemented
