### ISSUE TITLE
SV_CVAR restrictions not being respected

### ISSUE THREAD

**Issue by acelad88** [rtcwmp-com/rtcwPro#252]
Feature #15 implemented server cvar restrictions, and I can see that the defaultcomp.cfg has `command sv_cvar r_picmip "IN 0 3"`

However, I am able to connect to a server (`/connect hyperion-gaming.net:17600;password pikachu`) and set cvars to way beyond these limits, giving a competitive advantage that would be considered cheating.

### A normal cfg with r_picmip = 3:
![112936-hateful8Adlad-te_frostbite](https://user-images.githubusercontent.com/47744750/105029765-ad822780-5a4a-11eb-8190-79f16872eeb5.jpg)

### A cfg with r_picmip = 20:
![112915-hateful8Adlad-te_frostbite](https://user-images.githubusercontent.com/47744750/105029763-ace99100-5a4a-11eb-93c4-3ef5eba01104.jpg)

**Comment by natelo** [comment]
Problem is that r_ variables are intercepted by engine so by the time they're cascaded to logic, it's too late as they're already set.

There's two ways that I can think off as how it could be done:
1) By reloading game after logic picks up unsupported values but that's a hacky way and a possible stability issue - essential two vid_restarts.
2) Sorting on engine level but that would require everyone to use client. 

Both options have issues.. If someone sees any other option, feel free ..

**Comment by krazykaze81** [comment]
One thing we could do in the meantime is remove the nopicmip flag on the tree textures - that would at least keep trees valid and not allow people to see through them

**Comment by acelad88** [comment]
Thanks for the speedy responses guys!

@natelo: Out of the two options, we could survey the community but given that the entire competitive scene is on Discord I don't think it would be a problem for people to use a new client if required. While we're on this topic, maybe it's worth thinking big and looking at building an anti-cheat replacement for punkbuster?

@krazykaze81: That may help indeed, and a temporary patch is better than nothing while a decision is being made on how to achieve the above.

**Comment by krazykaze81** [comment]
Using picmip 10 and shader with nopicmip on trees

![shot0000](https://user-images.githubusercontent.com/45461774/105093320-89394180-5a70-11eb-99e5-dfc3ca2c129c.jpg)

**Comment by natelo** [comment]
I guess we need to ask comminity. If they’re willing to accept client, we can easily address this in a timely manner.

**Comment by S4NDM4NN** [comment]
The values are set, but could we just kick the client after x time if they do not comply with the restrictions?

**Comment by natelo** [comment]
Hey S4ND :) 
It would be an option, but not sure if they would want to go down that path?

Personally I would go with client option as that opens tons of possibilities..but that’s just me.

**Comment by krazykaze81** [comment]
> The values are set, but could we just kick the client after x time if they do not comply with the restrictions?

That would definitely be an option before we can come out with client

**Comment by krazykaze81** [comment]
Testing complete
