### ISSUE TITLE
Auto pick-up items disables randomly

### ISSUE THREAD

**Issue by acelad88** [rtcwmp-com/rtcwPro#255]
I've had this happen twice now where I can no longer pick up ammo or health automatically, and /handicap 100 is set already. There don't seem to be any obvious triggers (maybe vid_restart?) and the only way to resolve it seems to be to exit and restart the game (/reconnect does not help).

Example video: https://www.twitch.tv/videos/880189969?t=0h5m39s

**Comment by natelo** [comment]
Is the second time also captured in this video? 

If not, can you recall when it happen, if you were revived just before it?

**Comment by acelad88** [comment]
@natelo: Unfortunately I don't have a clip for the other time it occured, and no it's not in this video. Being revived could well be a trigger - it was shortly after being revived that I noticed it happening in the clip above.

**Comment by natelo** [comment]
That much I noticed that is why I am asking if you recall that being the case in that instance, that is not captured in the video?

**Comment by acelad88** [comment]
@natelo: I can't remember if it was after a revive in the first case, but one thing that I'm pretty sure about is that in both cases, I noticed the issue in the **first round of play**. I tend to record all of my gameplay (just unlucky that I'd forgotten to the first time this happened) so next time if it happens again I'll clip it and add the repro conditions to this bug :).

**Comment by krazykaze81** [comment]
The one thing I can think about is on the ammo I ported Magic Ammo check from ET so players do not pick up ammo when they have a full set of ammo/clips.  This could have a bug in it for ammo but I don't think it would affect health.  The code is in BG_CanItemBeGrabbed

			if (item->giTag == WP_AMMO) // magic ammo for any two-handed weapon
			{
				return BG_AddMagicAmmo((playerState_t*)ps, ps->persistant[PERS_TEAM]); // RtcwPro - check to see if player needs the ammo (ET Port)
			}

**Comment by acelad88** [comment]
@krazykaze81: That sounds feasible, although one of my teammates has just mentioned that this issue has happened years ago on OSP even, but he has no clue why it occurs. Maybe I've just been unlucky that it's happened to me twice in a week. Just thought I'd let you know so you can maybe rule out any recent commits from causing this.

**Comment by natelo** [comment]
It happens if you have connection issues like packet loss but in that case you're aware of it. What it does not is, that it happens twice under ideal circumstances. There's something not being set somewhere .. round is imho irrelevant, probably it's tied to revive but can't really say since there's nothing to compare against. 

I've looked into client, items and combat stuff but nothing special pops up from first glance.. so maybe just try to keep an eye and if it happens again, try to remember if there was any kind of event (died->revived / respawned / whatever may seem important).

**Comment by acelad88** [comment]
> Also, just to confirm - full respawn does not clear the issue?

Nope, no matter how many times I respawn it seems to persist, and only a game restart resolves it. I'll experiment to try to repro over the next few days.

**Comment by krazykaze81** [comment]
I think this has been figured out that handicap is getting set to zero

**Comment by acelad88** [comment]
> I think this has been figured out that handicap is getting set to zero

I can confirm that the last few times this has happened, setting /handicap 100 has resolved it. Does not seem specific to rtcwpro, but ofc is one more legacy bug that would be nice to see the back of!

**Comment by krazykaze81** [comment]
Tested and working in version 1.2 - Tarator removed handicap altogether.
