### ISSUE TITLE
Drop weapon issue

### ISSUE THREAD

**Issue by krazykaze81** [rtcwmp-com/rtcwPro#282]
When LT has ammo packs out and you drop your weapon it will autoswitch to pistol instead of keeping packs in the hand.  Need to verify that OSP does this.

**Comment by krazykaze81** [comment]
Confirmed OSP - when you have ammo packs and drop SMG it stays on ammo pack (unless cg_autoswtich 1)

Confirmed Pro - when you have ammo packs and drop SMG it switches to Pistol - that isn't right

**Comment by natelo** [comment]
It just requires holdable check - to see if player is holding something
..should be an easy fix.
