### ISSUE TITLE
Prevent spinning scripts

### ISSUE THREAD

**Issue by krazykaze81** [rtcwmp-com/rtcwPro#283]
"com_maxfps 60; wait 2; cl_yawspeed 11250; +left; wait 2; -left;cl_yawspeed 140; com_maxfps 125"  -- script example I think we could clamp cl_yawspeed in the configs to upper and lower bounds

**Comment by natelo** [comment]
I think this is unneeded as cvar restrictions can clamp cvars so there's really nothing to do here.

**Comment by krazykaze81** [comment]
We do have cl_yawspeed clamped to 180 max so that may be all we need.  Closing for now.
