### ISSUE TITLE
Callvote map causing map reload over and over

### ISSUE THREAD

**Issue by krazykaze81** [rtcwmp-com/rtcwPro#299]
Develop branch - connect to server and change maps using /callvote - client will not load the map and the map loads over and over (this could be a local issue of mine but I would like someone to confirm)

Also getting this issue running wolfded from Visual Studio and client connects to it

**Comment by wolf6542** [comment]
Confirmed in the alpha release.

**Comment by krazykaze81** [comment]
I think this may be a Windows OS issue only.  Nate's alpha server is working fine

**Comment by krazykaze81** [comment]
Turns out this too many maps on server - easy to fix?

**Comment by krazykaze81** [comment]
Fixed by Tara
