### ISSUE TITLE
Vote configs

### ISSUE THREAD

**Issue by wolf6542** [rtcwmp-com/rtcwPro#304]
Since there has been an increasing demand for more cfg customization, because afaics server admins cannot granulate cfgs beyond g_mapconfigs for purposes like 3o3 or 6o6 etc - it might be a good idea to tie custom configs to callvote, or do something similar to rtcwPub (g_voteconfigs).

**Comment by natelo** [comment]
That already exists. It’s callvote config .. Currently it just looks at
wrong path so needs to be fixed.
