### ISSUE TITLE
(1.1.2) FFE causes instant damage 

### ISSUE THREAD

**Issue by acelad88** [rtcwmp-com/rtcwPro#307]
**Describe the bug**
FFEing caused instant (high amount of) damage to opponent who had just spawned.
Server: connect rtcwpro.msh100.uk:27961;password gatherde
Map: te_escape2
Location: Lower MG

**To Reproduce**
To reproduce the exact scenario in the video below (may not be map-specific):
1. Have an enemy stand at MG
2. Fire FFE at his feet
3. Observe whether he dies instantly

**Expected behavior**
No damage caused to opponent as smoke had not even appeared yet.

**Screenshots or videos**
https://clips.twitch.tv/ProudCovertDogeKeyboardCat-xppKMQCUx_6bixDt

**Comment by acelad88** [comment]
Update: This looks like it's due to the map, not the mod. Kris posted a video on OSP of a similar occurence: https://streamable.com/bu355c

**Comment by krazykaze81** [comment]
There is some specific logic code (vanilla) that deals with players while they're behind the MG and I think this is the issue.  I think this is MG42 specific not map

**Comment by krazykaze81** [comment]
Fixed in 1.2.7
