### ISSUE TITLE
Defensive dynamites being defused prompts notification

### ISSUE THREAD

**Issue by acelad88** [rtcwmp-com/rtcwPro#308]
**Describe the bug**
RtCWPro 1.1.2.
When the defending team arms a "fake" dynamite in front of an objective e.g. Ice service door, then the attacking team defuses it, the "dynamite defused" notification comes up.

**To Reproduce**
1. Spawn Allied Engineer on Ice and plant dynamite at service door
2. Spawn Axis Engineer and defuse it
3. Observe that visual and audio notification appears

**Expected behavior**
In vanilla this does not prompt a notification, and I'd say this is better as it avoids confusion.

**Screenshots or videos**
https://clips.twitch.tv/SpikyMoldyNightingaleRaccAttack-Cppcp3Yn6cOzrR5z

**Comment by krazykaze81** [comment]
Easy fix - I will add it in

**Comment by krazykaze81** [comment]
Fixed
