### ISSUE TITLE
/toggle <cvar int>

### ISSUE THREAD

**Issue by wolf6542** [rtcwmp-com/rtcwPro#327]

**Comment by natelo** [comment]
There’s /vstr already, else what is this suppose to be?

**Comment by wolf6542** [comment]
I had a request for this from people because /vstr wasn't viable. Some cvars are overflowing Cbuf_InsertText when used with vstr (don't know why).

**Comment by wolf6542** [comment]
Redundant..
Cvar_Toggle_f
