### ISSUE TITLE
Cvar restrict cuts execution incorrectly

### ISSUE THREAD

**Issue by wolf6542** [rtcwmp-com/rtcwPro#346]
/bind key "+sprint; set cg_fov 115" will return as fov value not allowed even though it's in range (in 90 120).

![safafaf](https://user-images.githubusercontent.com/60988055/127372921-3f119c99-e730-4a5f-8705-6293e0f6e547.png)

**Comment by krazykaze81** [comment]
Work-around

/bind key "+sprint; cg_fov 115" without using set
