### ISSUE TITLE
bullet knockback inconsistent

### ISSUE THREAD

**Issue by murkey1337** [rtcwmp-com/rtcwPro#349]
**Describe the bug**
between mp40 and thompson and osp vs rtcwpro there is huge differences in terms of knock back. Posted videos down below.

**Expected behavior**
I think they should be close to identical as OSP as possible. Thompson is already the "weaker" gun technically due to having larger spread and less accurate and having it not knockback as much as mp40 is pretty tough for when you're on offense.

**Screenshots or videos**
If applicable, add screenshots or video links to help explain your problem.

OSP With mp40 shooting back of player 10 times then checking distance from the wall for reference:
https://streamable.com/uhbl2d

RTCWPRO With mp40 shooting back of the player 10 times with g_knockback "100"
https://streamable.com/hray0v

RTCWPRO With mp40 shooting the back of the player 10 times with g_knockback "500"
https://streamable.com/e6wl7u

OSP shooting with thompson 10 times in the back then checking distance from the wall for reference:
https://streamable.com/37nztm

RTCWPRO shooting with thompson 10 times in the back of the player and then checking distance g_knockback "500"
https://streamable.com/oo9i0b

**Comment by wolf6542** [comment]
There is no way to know how if at all OSP changes damage and knockback. In a vanilla scenario, knockback = damage, so the weapon discrepancy shouldn't exist.

**Comment by krazykaze81** [comment]
Closed per #358
