### ISSUE TITLE
Objective stats are not saved

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#352]
Player stats submitted to the api don't seem to be tracking obj_destroyed and obj_captured

**Expected behavior**
Played 33 games under new version and expected to have at least some  (i capture a lot)

**Screenshots or videos**
The following JSON is summed over 33 games. 
https://rtcwproapi.donkanator.com/player/22b0e88467093a63d5dd979eec2631d1?22b0e88467093a63d5dd979eec2631d1

I have checked before over thousands of games - obj_captured is always 0
obj_destroyed - only 1 of 1134 older tests

murkey too - https://rtcwproapi.donkanator.com/player/0ACA00499288FB

**Comment by rtcw-nihi** [comment]
just another thing that was forgotten about. thanks for the reminder

**Comment by rtcw-nihi** [comment]
3e28cc3032946a5f7aa30f76722db9e02ef5274b
