### ISSUE TITLE
g_knockback 500 reduces overall explosive knockback

### ISSUE THREAD

**Issue by rtcw-online** [rtcwmp-com/rtcwPro#358]
There is some code in g_knockback which is manipulating the knockback for explosives based on using a value of g_knockback 100.

```
        // L0 - Now by default knockback is set to 100 (was 1000) so if it's not touched
	// multiply nade and AS to 1000 so it acts and feels like default
	if (dflags & DAMAGE_RADIUS) {
		if (g_knockback.integer <= 100)
			knockback *= 10;
	} // End
```

Match configs have been updated to use 500, which means this overall explosive knockback has been reduced.

I can see vanilla has a `g_knockback` value of 1000, does anyone also have any insight into why `g_knockback` has been changed to 500? and before that 100?

My understanding of the code is that `knockback` based on damage value and capped at 200. Meaning `g_knockback` can just be set to 1000 and the block above removed. That is unless their is evidence osp changed how vanilla knockback worked.

Thanks

crumbs

**Comment by natelo** [comment]
Knockback is applied on damage for mainly two scenarios: Explosions and when you are shot at.

“Shot at” bit was reduced to 100 while other damage stayed default. That meant, that on exploding nades, pf arc and alike stuff, behaviour was the same as in vanilla while being shot at would not push players back too much as that rendered in some scenarios a really slugish feeling.

**Comment by rtcw-online** [comment]
Yes that makes sense, but `g_knockback` has now been set to 500 in mod.cfg and in match configs making that block no longer fix knockback to the correct values for explosives.

**Comment by natelo** [comment]
Actual knocback is locked to 200. Only explosive stuff is post processed and (g_knocback) value depended. 

Setting it to 500 will shown as half-effect. My experience was that between 800 and 1000 (default) is Ok. Albeit actual feeling of effect can vary as at least on 1.0 math went off when they've set higher speeds as momentum or stuff like bunny jumps. 

As far as why it has been set to less, can't comment on that.
Ref: https://github.com/rtcwmp-com/rtcwPro/commit/4d62fbe22badac43698a5b7cad37371108d51fcf#diff-f0bff1c1d760e88bd72d60ab43e2b7c9b0a76e0b25dec5c8bd4a454ff8ec9c12

**Comment by krazykaze81** [comment]
When using knockback values of 800/1000 the overall knockback from weapons is so strong that no offensive team stands a chance against a crossfire.  We have tested value of 500 and it seems to be a good balance so far.

**Comment by natelo** [comment]
What weapons exactly? SMGs or we're talking explosives like nades, pf, mortars?

As it should affect later and always have just a small nudge/push on SMGs/Handguns or Knifes regardless of value set in cvar. If that's not the case then something is not working as intended.

**Comment by krazykaze81** [comment]
SMG fire with antilag turned on feels like it pushes players back more which is why the knockback values came into question.
