### ISSUE TITLE
Include server info into UI

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#361]
**Is your feature request related to a problem? Please describe.**
What server are you on?
 ... Mm ... I dunno

**Describe the solution you'd like**
Include sv_hostname and ip into scoreboard or limbo

**Describe alternatives you've considered**
/some_serverinfo_var_nobody_remembers

**Additional context**
Bonus:make ip copy-able to clipboard

**Comment by krazykaze81** [comment]
Use /serverinfo or /serverstatus for now

**Comment by krazykaze81** [comment]
Added servername to scoreboard along with full date - we only had the time
https://github.com/rtcwmp-com/rtcwPro/commit/8381e8aabe130371fc69e8a5b13b7ec4dbfdc8b4
