### ISSUE TITLE
Stats - gamestats/gameinfo does not have clear handling of full holds

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#369]
**Describe the bug**
round 1 does not always have a winner (not necessary)
round 2 winner should be Axis, Allied, or draw

**To Reproduce**
check stats for full hold matches , they would say Allies on ice or Axis on cypher. 

**Expected behavior**
It is possible for a human to infer a winner - if the r2 timelimit ~ map limit and r2 winner is defense - then draw
It would be better if Round2 winner was displayed as Axis, Allied, or Draw

**Screenshots or videos**
This is not map specific.
ice
Gamelog: https://rtcwproapi.donkanator.com/gamelogs/16331547262
Gameinfo https://rtcwproapi.donkanator.com/matches/16331547262 - winner is allied . timelimit was 10 (r1 full hold) and no obj Capture.
cypher
Gamelog: https://rtcwproapi.donkanator.com/gamelogs/16331436612
Gameinfo https://rtcwproapi.donkanator.com/matches/16331436612 - winner is axis. timelimit was 10 (r1 full hold) and no obj Capture.

**Additional context**

**Comment by wolf6542** [comment]
I've also noticed some times console will report clock wrongly. Could be relate
![shot0000](https://user-images.githubusercontent.com/60988055/135924091-f8f289c6-d865-4e52-b746-f889b834e1d1.jpg)
d.
