### ISSUE TITLE
Stats - mp_village winner is not displayed properly

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#370]
**Describe the bug**
1. Stats for village matches do not indicate that allied was a winner. 
2. Village for some reason has multiple ObjCapture events at the end of the round. Expecting 1.

**To Reproduce**
Play out village round where allies win round 2. 

**Expected behavior**
Round2 stats contain Allied in winner

**Screenshots or videos**
Gamelog: https://rtcwproapi.donkanator.com/gamelogs/16329390782 - see the end of the file. Objective is captured multiple times . Should be 1 . Winner should be allies
Gameinfo https://rtcwproapi.donkanator.com/matches/16329390782 

Gamelog: https://rtcwproapi.donkanator.com/gamelogs/16328570392 
Gameinfo https://rtcwproapi.donkanator.com/matches/16328570392

**Comment by krazykaze81** [comment]
FIxed 1.2.9
