### ISSUE TITLE
Stats - dynamite based maps and mp_password do not display proper winner in gameinfo

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#371]
**Describe the bug**
dynamite based maps (and timelimit map mp_password) have different behavior in providing winner in stats/gameinfo

The winner of round1 is displayed when objective based maps do not provide this info
The winner of round1 is NOT displayed when r1 was full hold
The winner is only displayed if the round2 was held by defense.

**To Reproduce**
play out a round of dynamite based map and see server side json stats

**Expected behavior**
Round 2 should display a winner 100% of the time

**Screenshots or videos**
broundorf example
Gamelog: https://rtcwproapi.donkanator.com/gamelogs/16331107772
Gameinfo https://rtcwproapi.donkanator.com/matches/16331107772 - timelimit is default, so r1 was likely fullhold. No winner in R2 , but it was finished under 7 minutes via gamelog

![image](https://user-images.githubusercontent.com/10265890/135925837-fe667eaf-5b8e-4e30-b526-385cd7d0d700.png)

**Comment by krazykaze81** [comment]
Fixed 1.2.9
