### ISSUE TITLE
Stats - obj_destroyed is never counted and there's not obj_destroyed event in gamelog

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#372]
**Describe the bug**
Cannot find a single player with obj_destroyed > 0 over lifetime
On dynamite based maps there's no gamelog event that says objective was destroyed (probably cause of #1)

**To Reproduce**
https://rtcwproapi.donkanator.com/player/search/donk
grab longer guids
https://rtcwproapi.donkanator.com/player/22b0e88467093a63d5dd979eec2631d1

In gamelog - you see where objectives are planted, but never destroyed?
https://rtcwproapi.donkanator.com/gamelogs/16333680652

**Expected behavior**
have obj_destroyed count for individuals... probably better if it means MAIN or objective (like assault tower, broundorf generator or , say for now, arbitrary radar 1 on base)

**Comment by krazykaze81** [comment]
I was able to uncomment the line of code that does objDestroyed and it seems to work
[gameStats_match_1639963760_round_1_mp_base.json.txt](https://github.com/rtcwmp-com/rtcwPro/files/7742060/gameStats_match_1639963760_round_1_mp_base.json.txt)
