### ISSUE TITLE
cg_muzzleflash 1 doesn't work(?)

### ISSUE THREAD

**Issue by wolf6542** [rtcwmp-com/rtcwPro#374]

**Comment by krazykaze81** [comment]
Found this in the code from OSPx

`{ "cg_muzzleFlash",           qtrue,  qtrue,  NULL,        ":^7 1 = yours OFF, enemies ON   / 0 = yours OFF, enemies OFF"},`

`	// OSPx - Disable muzzleFlash if they have it off..
	// NOTE: Patched for zoomed FOV


	if ( isPlayer || !cg_muzzleFlash.integer || cg.zoomedFOV) {

		flash.hModel = 0;
	}`

**Comment by krazykaze81** [comment]
Fixed with https://github.com/rtcwmp-com/rtcwPro/commit/44391af50541eef4783c70f101ff6f6350f734a9
