### ISSUE TITLE
Stats: missing some matches submissions to rtcwproapi pipeline

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#381]
**Describe the bug**
On occasion, RTCWPro server does not submit match json to RTCWPROapi and it's unclear why.
Occurences of missing Round 1(not critical) and round 2 were spotted
API logs show that traffic never came in from RTCWPRO server
Happens in different regions and servers/dockers
Server logs are missing a line like "UPLOADED intake/..." or "FAILED ..."

**To Reproduce**
unclear

**Expected behavior**
Log an attempt to submit json
Submit json stats to RTCWPROApi
If submission is not successful (exception or not 200 http return code), log AND try again once
If submission is not successful, log and dump to disk

**Screenshots or videos**
Normal submission example:
![image](https://user-images.githubusercontent.com/10265890/147957277-596911b3-928e-4209-ac09-8b40f491cb0a.png)

Missing submission example:
![image](https://user-images.githubusercontent.com/10265890/147957312-12e87e88-d9eb-4353-b4d9-1598717c7c86.png)

**Comment by krazykaze81** [comment]
Implemented retry loop - 3 tries to submit before failing - future change would be to have a queue and save the json files until they are able to be submitted
