### ISSUE TITLE
Stats: new vars like dyn_planted are not being reset

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#382]
**Describe the bug**
Plants and objective counts in json/stats have values that are too high

**To Reproduce**
Stay on the server as engineer and check stats later - a person can have 5-6-7-8 plants per match

**Expected behavior**
Plants and objectives reset to 0 after every round 2

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/10265890/148816762-463505da-bf18-415e-8541-388c307b5798.png)

src\game\g_stats.c has a function G_deleteStats that does not have the following vars zeroed out

client->sess.dyn_planted,
client->sess.dyn_defused,
client->sess.obj_captured,
client->sess.obj_destroyed,
client->sess.obj_returned,
client->sess.obj_taken

I further compared the list of all vars and it should have maybe
sess.knifeKills
sess.poisoned

The functions i compared are below

void G_deleteStats( int nClient ) {
	gclient_t *cl = &level.clients[nClient];

	cl->sess.damage_given = 0;
	cl->sess.damage_received = 0;
	cl->sess.deaths = 0;
	cl->sess.rounds = 0;
	cl->sess.kills = 0;
	cl->sess.suicides = 0;
	cl->sess.team_damage = 0;
	cl->sess.team_kills = 0;
	// Reset new ones as well
	cl->sess.headshots = 0;
	cl->sess.med_given = 0;
	cl->sess.ammo_given = 0;
	cl->sess.gibs = 0;
	cl->sess.revives = 0;
	cl->sess.acc_hits = 0;
	cl->sess.acc_shots = 0;
	cl->sess.killPeak = 0;

	memset( &cl->sess.aWeaponStats, 0, sizeof( cl->sess.aWeaponStats ) );
	trap_Cvar_Set( va( "wstats%i", nClient ), va( "%d", nClient ) );
}

to 

void G_jstatsByPlayers(qboolean wstats) {

    int i, j, eff,rc;
	float tot_acc = 0.00f;
	char* s;
	gclient_t *cl;
	char n1[MAX_NETNAME];
	char n2[MAX_NETNAME];
	char pGUID[64];
    unsigned int m, dwWeaponMask = 0;
	char strWeapInfo[MAX_STRING_CHARS] = { 0 };
	time_t unixTime = time(NULL);
    json_t* jdata;
    json_t* jstats;
    json_t* jplayer;
    json_t* jcat;
    json_t* weapOb;
    json_t *root = json_object();
    json_t* weapArray;

    jstats =  json_array();

        for ( j = 0; j < level.numPlayingClients; j++ ) {
            jplayer = json_object();
			cl = level.clients + level.sortedClients[j];

			if ( cl->pers.connected != CON_CONNECTED ) {
				continue;
			}
			DecolorString(cl->pers.netname, n1);
			SanitizeString(n1, n2);
			Q_CleanStr(n2);
			n2[15] = 0;

			eff = ( cl->sess.deaths + cl->sess.kills == 0 ) ? 0 : 100 * cl->sess.kills / ( cl->sess.deaths + cl->sess.kills );
			if ( eff < 0 ) {
				eff = 0;
			}
			sprintf(pGUID,"%s",cl->sess.guid);
            i = cl->sess.sessionTeam;
            jdata = json_object();
           // json_object_set_new(jdata, "GUID", json_string(cl->sess.guid));
            json_object_set_new(jdata, "alias", json_string(n2));
            json_object_set_new(jdata, "team", json_string((i == TEAM_RED) ? "Axis" : "Allied"  ));
            json_object_set_new(jdata, "start_time", json_integer(cl->sess.start_time));   // need to fix
           // json_object_set_new(jdata, "end_time", json_integer(cl->sess.end_time));   // need to fix
            x json_object_set_new(jdata, "num_rounds", json_integer(cl->sess.rounds));

            jcat = json_object();

            x json_object_set_new(jcat, "kills", json_integer(cl->sess.kills));
            x json_object_set_new(jcat, "deaths", json_integer(cl->sess.deaths));
            x json_object_set_new(jcat, "gibs", json_integer(cl->sess.gibs));
            x json_object_set_new(jcat, "suicides", json_integer(cl->sess.suicides));
            x json_object_set_new(jcat, "teamkills", json_integer(cl->sess.team_kills));
            x json_object_set_new(jcat, "headshots", json_integer(cl->sess.headshots));
            x json_object_set_new(jcat, "damagegiven", json_integer(cl->sess.damage_given));
            x json_object_set_new(jcat, "damagereceived", json_integer(cl->sess.damage_received));
            x json_object_set_new(jcat, "damageteam", json_integer(cl->sess.team_damage));
            x json_object_set_new(jcat, "hits", json_integer(cl->sess.acc_hits));
            x json_object_set_new(jcat, "shots", json_integer(cl->sess.acc_shots));
            xx json_object_set_new(jcat, "accuracy", json_real(((cl->sess.acc_shots == 0) ? 0.00 : ((float)cl->sess.acc_hits / (float)cl->sess.acc_shots) * 100.00f)));
            x json_object_set_new(jcat, "revives", json_integer(cl->sess.revives));
            x json_object_set_new(jcat, "ammogiven", json_integer(cl->sess.ammo_given));
            x json_object_set_new(jcat, "healthgiven", json_integer(cl->sess.med_given));
            json_object_set_new(jcat, "poisoned", json_integer(cl->sess.poisoned));
            json_object_set_new(jcat, "knifekills", json_integer(cl->sess.knifeKills));
            x json_object_set_new(jcat, "killpeak", json_integer(cl->sess.killPeak));
            xx json_object_set_new(jcat, "efficiency", json_real(eff));
            // The following objects are not stored over multiple rounds....need to add to g_session if we want these to reflect multiple rounds
            json_object_set_new(jcat, "score", json_integer(cl->ps.persistant[PERS_SCORE]));
            json_object_set_new(jcat, "dyn_planted", json_integer(cl->sess.dyn_planted));
            json_object_set_new(jcat, "dyn_defused", json_integer(cl->sess.dyn_defused));
            json_object_set_new(jcat, "obj_captured", json_integer(cl->sess.obj_captured));
            json_object_set_new(jcat, "obj_destroyed", json_integer(cl->sess.obj_destroyed));
            json_object_set_new(jcat, "obj_returned", json_integer(cl->sess.obj_returned));
            json_object_set_new(jcat, "obj_taken", json_integer(cl->sess.obj_taken));

            weapArray = json_array();
            i = cl->sess.sessionTeam;
            for (m = WS_KNIFE; m < WS_MAX; m++) {
                if (cl->sess.aWeaponStats[m].atts || cl->sess.aWeaponStats[m].hits ||
                    cl->sess.aWeaponStats[m].deaths) {
                        dwWeaponMask |= (1 << i);
                        weapOb = json_object();
                        json_object_set_new(weapOb, "weapon", json_string((m >= WS_KNIFE && m < WS_MAX ) ? aWeaponInfo[m].pszName : "UNKNOWN" ));
                        json_object_set_new(weapOb, "kills", json_integer(cl->sess.aWeaponStats[m].kills));
                        json_object_set_new(weapOb, "deaths", json_integer(cl->sess.aWeaponStats[m].deaths));
                        json_object_set_new(weapOb, "headshots", json_integer(cl->sess.aWeaponStats[m].headshots));
                        json_object_set_new(weapOb, "hits", json_integer(cl->sess.aWeaponStats[m].hits));
                        json_object_set_new(weapOb, "shots", json_integer(cl->sess.aWeaponStats[m].atts));
                        json_array_append(weapArray, weapOb);
                        json_decref(weapOb);
                }
            }

            if (g_gameStatslog.integer & JSON_CATEGORIES) {
                json_object_update(jdata, jcat);
            }
            else {
                json_object_set(jdata, "categories", jcat);
            }

            if (wstats) {
                json_object_set(jdata, "wstats", weapArray);
                json_object_set(jplayer, pGUID, jdata);
                json_decref(weapArray);
            }
            else {
                json_object_set(jplayer, pGUID, jdata);
            }

            json_decref(jcat);
            json_decref(jdata);
            json_array_append(jstats, jplayer);
            json_decref(jplayer);

        }

**Comment by krazykaze81** [comment]
Fixed with commit https://github.com/rtcwmp-com/rtcwPro/commit/4103e66a9d8e8345aa4c553828568eee02984d26
