### ISSUE TITLE
Server crash (image)

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#389]
**Describe the bug**
Murkey's server crashing , log below

**Screenshots or videos**
![image](https://user-images.githubusercontent.com/10265890/151929848-fbf19b7e-a6b2-410c-9a68-594b6d1a8c58.png)

**Additional context**
Server is generally fine for days, but 1 out of 100 games it crashes at the end of the round with the error in the image

**Comment by krazykaze81** [comment]
Recreation for this is not working.  I have added debug prints to server log using g_statsDebug "1" to try to see if we can pinpoint where the issue happens.  I think the issue is related to writing to the stats file.

**Comment by krazykaze81** [comment]
Should be avoided with changes in #414
