### ISSUE TITLE
revive knockback bug

### ISSUE THREAD

**Issue by murkey1337** [rtcwmp-com/rtcwPro#401]
**Describe the bug** i think when player is revived they're entered in a temporary state of g_knockback 100, once the player can move again they enter back to their g_knockback 1000 state. Which makes knocking players down in specific parts of maps unfavorable when you should be able to hold your ground. For example: When you are allied on Ice in North halls and shoot a player at the top of the stairs who gets revived you should be able to knock the player down the steps with ease. Then the player has to come back up the stairs instead of charging you with godmode.

rtcwpro example where you can only knock them past angles after they can move again:
https://streamable.com/2xrom8

osp where your bullets immediately are working as intended with knockback and freshly vived:
https://streamable.com/j15fwn

**Comment by krazykaze81** [comment]
@murkey1337 what g_knockback setting is used in pro example?

**Comment by murkey1337** [comment]
both are 1000

**Comment by krazykaze81** [comment]
@murkey1337 can you try the pro example again on your end?  It looks like it's pushing players fine on my end. 
 Maybe try a flat surface on both OSP and Pro and compare the distances like you did a while back on ice. 
https://streamable.com/r8plg5

**Comment by krazykaze81** [comment]
I think they're about the same at least from our most recent discussion.  Closing this for now.
