### ISSUE TITLE
Silent airstrikes

### ISSUE THREAD

**Issue by murkey1337** [rtcwmp-com/rtcwPro#406]
silent airstrikes are happening *AFTER* you've spawned and the strike is being thrown, regardless of latency. While YES osp had silent airstrikes this is happening way more often than it should be. It's hard to determine the factor of what is causing it but there is clear sound/event issues with rtcwpro that are not just silent airstrikes, but silent doc grabs as well, based on when you respawn and when the docs are taken it will be silent. Same for returns, same for any event I believe.

https://streamable.com/revx78 

I've got around 8 ping to virginia and you can clearly hear the strike thrown yet makes no noise, confirmed with xill who died he didn't hear it as well it just sounded like a grenade landing on the floor

https://clips.twitch.tv/MoldyPoliteMacaroniJonCarnage-tVr-TdIvF9VmvXLz

taken from Xill's stream where you see the strike thrown and no airplane cue is being sent to his client.

**Comment by krazykaze81** [comment]
Changes made with commit 670d39cd6248918cd64bcfc9dcd9d7d23af1bb05
