### ISSUE TITLE
Server crash

### ISSUE THREAD

**Issue by donkz** [rtcwmp-com/rtcwPro#414]
**Describe the bug**
Server crash with this message 

```
ClientDisconnect: 11
Stats: writing disconnect event
Stats: writing game early exit
0 teams with 0 entities
23 items registered
-----------------------------------
Stats: writing FirstSpawn event
FS_FileForHandle Error Filename:
********************
ERROR: FS_FileForHandle: NULL
********************
----- Server Shutdown -----
Sending heartbeat to wolfmaster.idsoftware.com
Sending heartbeat to dpmaster.deathmask.net
Sending heartbeat to wolfmaster.s4ndmod.com
==== ShutdownGame ====
ShutdownGame:
------------------------------------------------------------
---------------------------
Server is not running.

```

**Comment by murkey1337** [comment]
0 1 8 38 140 32768 1 0 30 1 14 0 1 10 63 0 32768 3 32 19 0 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 17 125 32768 2 30
30 8 14 0 1
cmd  1599: tinfo 3 140 7 1 12 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 37 140 32768 1 30 26 0 14 0 1 8 37 86 32768 1 0 30 1 14 0 1 10 20 125 128 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 17 125 32768 2 30 30 8 14 0 1
cmd  1600: tinfo 3 140 7 1 12 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 37 140 32768 1 30 19 0 14 0 1 8 37 71 32768 1 0 30 1 14 0 1 10 20 125 128 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 22 125 32768 2 30 30 8 14 0 1
cmd  1601: tinfo 3 140 7 1 12 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 36 140 32768 1 30 15 0 14 0 1 8 36 2 32768 1 0 30 1 14 0 1 10 20 125 128 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 38 125 32768 2 30 30 8 14 0 1
cmd  1602: tinfo 3 140 7 1 12 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 36 140 32768 1 0 10 0 26
0 1 8 20 140 128 1 0 30 1 14 0 1 10 20 125 0 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 37 125 32768 2 30 30 8
14 0 1
cmd  1603: cs 578 "n\^>Joh^4n_M^dull^uins\t\1\model\multi_axis/redengineer1\head\redengineer1\c1\4\w\0\l\0\cc\255\mu\0\ref\0\scs\0"

cmd  1604: tinfo 3 140 7 1 12 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 36 140 32768 1 0 10 0 26
0 1 8 20 140 128 1 0 30 1 14 0 1 10 20 125 0 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 36 125 32768 2 30 30 8
14 0 1
cmd  1605: tinfo 3 140 7 1 11 125 32768 2 30 30 8 14 0 1 5 21 125 32768 0 3 1 4 7 0 1 7 35 140 32768 1 30 10 0 14 0 1 8 20 140 128 1 0 30 1 14 0 1 10 20 125 0 3 32 32 1 3 0 1 11 20 0 0 1 0 30 1 14 0 1 12 36 125 32768 2 30 30 8 14 0 1
cmd  1606: cs 15 "\numobjectives\4\defender\0\numspawntargets\0"

cmd  1607: cs 832 ""

cmd  1608: cs 833 ""

cmd  1609: tinfo 3 -10 6 7 96 44 0 1 24 8 1 13 0 0 10 20 125 0 3 32 32 1 3 0 0 11 48 140 128 1 0 30 1 14 0 0 1 48 140 128 1 0 30 1 14 0 0 8 48 140 128 1 0 30 1 14 0 0 5 48 125 128 0 4 0 4 7 0 0
cmd  1610: cs 13 "58595200"

ClientDisconnect: 11
Stats: writing disconnect event
Stats: writing game early exit
0 teams with 0 entities
23 items registered
-----------------------------------
Stats: writing FirstSpawn event
FS_FileForHandle Error Filename:
********************
ERROR: FS_FileForHandle: NULL
********************
----- Server Shutdown -----
Sending heartbeat to wolfmaster.idsoftware.com
Sending heartbeat to dpmaster.deathmask.net
Sending heartbeat to wolfmaster.s4ndmod.com
==== ShutdownGame ====
ShutdownGame:
------------------------------------------------------------
---------------------------
Server is not running.

$ sh: turning off NDELAY mode

**Comment by donkz** [comment]
This is how i understand it 

ClientDisconnect: 11   --- person #11 disconnected
Stats: writing disconnect event --- writing to stats that someone disconnected; match must have been on because condition of this function is g_gamestate.integer == GS_PLAYING
Stats: writing game early exit --- because maybe the teams are empty the map_restart initiated G_writeGameEarlyExit; Svcmd_ResetMatch_f has quite a few triggers around team size, shuffle, map switch
0 teams with 0 entities
23 items registered --- this only happens in G_InitGame in vmMain
Stats: writing FirstSpawn event --- G_loadMatchGame -> G_writeGeneralEvent further down in G_InitGame
FS_FileForHandle Error Filename:
********************
ERROR: FS_FileForHandle: NULL --- these 3 lines are all related to one failure
